IN: Messaging #87
hatchways/team-breadsticks pull request #102
Opened 2021-10-06 00:53 UTC by jstyle5

### What this PR does (required):
- Issue Link: https://github.com/hatchways/team-breadsticks/issues/87
- Created `conversation context`
- Refactored `seed` related files.

### Screenshots / Videos (required):
#### Desktop version (Assume the logged-in user is `DemoUser`, and he already has 3 conversations)
- The latest message for `DemoUser` is `DemoUser ---> Test3`. So, it is placed at the top of the `ChatSideBanner`.
>
![Screen Shot 2021-10-05 at 17 24 03](https://user-images.githubusercontent.com/54833010/136121609-8129306c-04ad-426f-b085-38b221674be0.png)
---

#### Desktop version (After clicking the conversation with `Test3` (ActiveConvo: Test3))
![Screen Shot 2021-10-05 at 17 29 57](https://user-images.githubusercontent.com/54833010/136122034-3569b90f-269c-4951-95ec-8cd892983a79.png)
---

#### Desktop version (After sending a message to `Test3`, the latestMessage is also updated)
![Screen Shot 2021-10-05 at 17 30 45](https://user-images.githubusercontent.com/54833010/136122125-b18ffdb0-d756-4d15-814b-5c230834170c.png)
---

#### Desktop version (After clicking the conversation with `Test1` (ActiveConvo: Test1))
![Screen Shot 2021-10-05 at 17 32 32](https://user-images.githubusercontent.com/54833010/136122232-dce4dcf1-03fd-43c8-b0bd-a49afaa61065.png)
---

#### Desktop version (After sending a message to `Test1`, the latestMessage is also updated. And, the `ChatBox(Conversation with Test1`) is placed at the top of the `ChatSideBanner`.
![Screen Shot 2021-10-05 at 17 36 44](https://user-images.githubusercontent.com/54833010/136122591-f9234a73-6f12-4430-a62a-a141851234ee.png)
---

#### Desktop version (Open a new browser and log-in as `Test1`, you can see the message from `DemoUser` that was just sent before)
![Screen Shot 2021-10-05 at 17 39 15](https://user-images.githubusercontent.com/54833010/136122844-56e7818e-da88-4d10-ad72-fcb4ad2652d5.png)
---

#### Mobile version (Assume the logged-in user is `DemoUser`, and he already has 3 conversations)
![Screen Shot 2021-10-05 at 17 42 33](https://user-images.githubusercontent.com/54833010/136122983-a92a3742-ed98-4d85-8627-45bb3552053c.png)
---

#### Mobile version (After clicking the conversation with `Test2 (ActiveConvo: Test2)`
![Screen Shot 2021-10-05 at 17 43 42](https://user-images.githubusercontent.com/54833010/136123057-1ac922ee-58da-4971-bb13-a3ca18a750c4.png)
---

#### Mobile version (After sending a message to `Test2`)
![Screen Shot 2021-10-05 at 17 44 25](https://user-images.githubusercontent.com/54833010/136123146-7646379e-bfdf-491c-86cf-0b266ff92d18.png)
---

#### Mobile version (If you want to go back to `ChatSideBanner`, swipe the screen from the left to the right)
![Screen Shot 2021-10-05 at 17 45 42](https://user-images.githubusercontent.com/54833010/136123367-1e8a0735-de05-4f7f-b1cb-3ad84732b059.png)
---

#### Mobile version (After sending a message to `Test2`, the latestMessage is also updated. And, the `ChatBox(Conversation with Test2`) is placed at the top of the `ChatSideBanner`.
![Screen Shot 2021-10-05 at 17 48 18](https://user-images.githubusercontent.com/54833010/136123523-959cf240-b3ec-4dc3-a728-1e8c69fd250e.png)

#### Mobile version (Open a new browser and log-in as `Test2`, you can see the message from `DemoUser` that was just sent before)
![Screen Shot 2021-10-05 at 17 51 33](https://user-images.githubusercontent.com/54833010/136123645-53c70165-b82e-48fb-bb13-220982a5bed6.png)
---

### Any information needed to test this feature (required):
- In order to create `Conversation`, **users must have their own `Profiles`.**
- Go into the server directory `cd server`
- Create `.env`, or if it exists, create your environment variables. `JWT_SECRET="Your JWT SECRET"
MONGO_URI="Your MongoDB URI"`
- Run `npm run seed` to import mock-data (NOTE: Whenever this command is executed, it will first remove all existing documents in `User`, `Profile`, `Conversation`, and `Message` collections. Then, it will insert mock-data automatically)
- Run `npm run dev` and test routes with Postman
- Since these routes are private, you need to log in first.

### Any issues with the current functionality (optional):
- `Search` feature is not implemented with this version. So, users can exchange messages within existing conversations only for now.
- Since `socket.io` is not set up with this current version, the real-time conversation feature is not considered.
- `Online status` and `Number of unread messages` are not considered.

2021-10-06 11:30 UTC, ezeilo-su commented
There's a conflict to be resolved in this PR, @jstyles5

2021-10-06 12:31 UTC, ezeilo-su requested changes
Well done on this one :+1: 
Just implement the requested changes before approval.
Happy coding!

2021-10-06 12:31 UTC, ezeilo-su commented on server/seed/seed.js
> +    console.log("Messages are deleted..");
Remove this console logs

2021-10-06 12:31 UTC, ezeilo-su commented on server/seed/seed.js
> +    console.error(err);
Remove this console logs

2021-10-06 12:31 UTC, ezeilo-su commented on server/seed/seed.js
> +  // DemoUser: testUsers[0], OtherUsers: testUsers[1] ~ testUsers[8]
Remove comments

2021-10-06 12:31 UTC, ezeilo-su commented on server/seed/seed.js
> +  // DemoUserProfile: testProfiles[0], OtherUserProfiles: testProfiles[1] ~ testProfiles[8]
Remove comments

2021-10-06 12:31 UTC, ezeilo-su commented on server/seed/seed.js
> +  // Initial conversation between demoUser and test1
Remove comments

2021-10-06 12:31 UTC, ezeilo-su commented on server/seed/seed.js
> +    console.log("MongoDB connection closed..".cyan.underline + "\n");
No console log is needed

2021-10-06 16:01 UTC, jstyle5 commented on client/src/App.tsx
> +            {/* <SocketProvider> */}
Restored

2021-10-06 16:07 UTC, jstyle5 commented on server/seed/seed.js
> +  // DemoUser: testUsers[0], OtherUsers: testUsers[1] ~ testUsers[8]
Applied

2021-10-06 16:07 UTC, jstyle5 commented on server/seed/seed.js
> +  // DemoUserProfile: testProfiles[0], OtherUserProfiles: testProfiles[1] ~ testProfiles[8]
Applied

2021-10-06 16:07 UTC, jstyle5 commented on server/seed/seed.js
> +  console.log(testProfiles.length + " testProfiles are created..");
Applied

2021-10-06 16:07 UTC, jstyle5 commented on server/seed/seed.js
> +  // Initial conversation between demoUser and test2
Applied

2021-10-06 16:10 UTC, jstyle5 commented
> Well done on this one 👍 Just implement the requested changes and resolve merge conflict before approval. Happy coding!

Thank you :)

2021-10-07 17:52 UTC, rajivtitus commented on client/src/context/useConvoContext.tsx
> +        produce((draft) => {
👍🏽

2021-10-07 18:20 UTC, rajivtitus approved these changes
Great work with this! 💯 

Just a minor optinal comment 😄

2021-10-07 19:05 UTC, jstyle5 commented on server/controllers/conversation.js
> +      .populate("user2Profile", "userId photos firstName lastName");
@rajivtitus I just tested it with `.populate(...).sort({'lastMessage.createdAt': -1}), but it seems that it's not working in the current `mongoose`? 🤔  (https://github.com/Automattic/mongoose/issues/4481)

2021-10-07 19:15 UTC, merged

2021-10-07 19:38 UTC, jstyle5 commented on server/controllers/conversation.js
> +      .populate("user2Profile", "userId photos firstName lastName");
@rajivtitus Many people do want `sort` feature after `populate`. It's very sad that is not supported. 😭